Remove CircleCI in favour for GitHub Actions
sonatype-nexus-community/scan-gradle-plugin pull request #177
Opened 2024-12-05 11:26 UTC by shaikhu

It relates to the following issue #s:
* Fixes #176 

cc @bhamail / @DarthHater / @guillermo-varela / @shaikhu

2024-12-05 16:20 UTC, bhamail requested changes
I don’t want to be a blocker, but could we wait to commit this PR until after a successful release has occurred using GitHub Actions?

2024-12-05 16:26 UTC, shaikhu commented
> I don’t want to be a blocker, but could we wait to commit this PR until after a successful release has occurred using GitHub Actions?

Sounds sensible to me 👍

2025-08-15 23:17 UTC, guillermo-varela approved these changes
+1

2025-08-15 23:18 UTC, guillermo-varela commented
> I don’t want to be a blocker, but could we wait to commit this PR until after a successful release has occurred using GitHub Actions?

I has happened! 😄

2025-08-15 23:21 UTC, merged